### ISSUE TITLE
Chromedriver error

### ISSUE THREAD

**Issue by namdeptrai2003** [moda20/facebook_page_scraper#2]
2024-07-01 16:24:55,561 - facebook_page_scraper.scraper - ERROR - Error at scrap_to_csv : There is no such driver by url http://chromedriver.storage.googleapis.com/LATEST_RELEASE_126.0.6478
Traceback (most recent call last):
  File "C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\facebook_page_scraper\scraper.py", line 174, in scrap_to_csv
    data = self.scrap_to_json()  # get the data in JSON format from the same class method
           ^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\facebook_page_scraper\scraper.py", line 90](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/facebook_page_scraper/scraper.py#line=89), in scrap_to_json
    self.__start_driver()
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\facebook_page_scraper\scraper.py", line 67](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/facebook_page_scraper/scraper.py#line=66), in __start_driver
    self.browser, self.proxy, self.headless).init(self.driver_install_config)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\facebook_page_scraper\driver_initialization.py", line 81](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/facebook_page_scraper/driver_initialization.py#line=80), in init
    driver = self.set_driver_for_browser(self.browser_name, driver_install_config=driver_install_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\facebook_page_scraper\driver_initialization.py", line 57](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/facebook_page_scraper/driver_initialization.py#line=56), in set_driver_for_browser
    return webdriver.Chrome(executable_path=ChromeDriverManager().install(),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\webdriver_manager\chrome.py", line 32](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/webdriver_manager/chrome.py#line=31), in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\webdriver_manager\manager.py", line 22](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/webdriver_manager/manager.py#line=21), in _get_driver_path
    driver_version = driver.get_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\webdriver_manager\driver.py", line 40](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/webdriver_manager/driver.py#line=39), in get_version
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\webdriver_manager\driver.py", line 64](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/webdriver_manager/driver.py#line=63), in get_latest_release_version
    validate_response(resp)
  File "[C:\Users\dimac\OneDrive\Desktop\pyvenv\venv1\Lib\site-packages\webdriver_manager\utils.py", line 79](file:///C:/Users/dimac/OneDrive/Desktop/pyvenv/venv1/Lib/site-packages/webdriver_manager/utils.py#line=78), in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url http://chromedriver.storage.googleapis.com/LATEST_RELEASE_126.0.6478

**Comment by lullu57** [comment]
You can solve this by downloading it directly from here:

https://googlechromelabs.github.io/chrome-for-testing/

and then providing the path directly using:

chrome_driver_path  = "pathGoesHere"
service = ChromeService(executable_path=chrome_driver_path)
driver = webdriver.Chrome(service=service)

Then it will start finding it cached
